version: '3.1'
services:
  db:
    container_name: mysql_container_docker
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: docker
      MYSQL_DATABASE: docker
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_PASSWORD: docker
    ports:
        - 3306:3306
    volumes:
    - microservices_volume:/var/lib/mysql
volumes:
  microservices_volume: